name       : perl-types-serialiser
version    : '1.01'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Types-Serialiser-1.01.tar.gz : f8c7173b0914d0e3d957282077b366f0c8c70256715eaef3298ff32b92388a80
homepage   : https://metacpan.org/pod/Types::Serialiser
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Types::Serialiser - simple data types for common serialisation formats
description: |
    This module provides some extra datatypes that are used by common serialisation formats such as JSON or CBOR. The idea is to have a repository of simple/small constants and containers that can be shared by different implementations so they become interoperable between each other.
rundeps    :
    - perl-common-sense
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
