name       : perl-types-serialiser
version    : 1.0
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/Types-Serialiser-1.0.tar.gz : 7ad3347849d8a3da6470135018d6af5fd8e58b4057cd568c3813695f2a04730d
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Types::Serialiser - simple data types for common serialisation formats
description: |
    This module provides some extra datatypes that are used by common serialisation formats such as JSON or CBOR. The idea is to have a repository of simple/small constants and containers that can be shared by different implementations so they become interoperable between each other.
rundeps    :
    - perl-common-sense
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
